### ISSUE TITLE
Question: bot not running?

### ISSUE THREAD

**Issue by tuanddd** [changesets/bot#24]
Hi all,

Seems to me that the bot is not running in every repo I know, both new and old (already configured)

Any ideas?

Thanks :)

**Comment by colebemis** [comment]
I'm having the same issue in the [primer/components](https://github.com/primer/components) repo

**Comment by jacobwgillespie** [comment]
Same issue as well, in https://github.com/styled-icons/styled-icons and related repos.

**Comment by mitchellhamilton** [comment]
This has been fixed. It seems that Vercel recently started redirecting from our domain on now.sh to a new domain on vercel.app rather than handling the request on the now.sh domain and GitHub treated the 308 as a failure rather than following the redirect. The domain has now been changed to the new vercel domain so after pushing a new commit, you should see the bot commenting again.

**Comment by sebm123** [comment]
### 

> [`_**``**_`]( #43 )
